interface Eatable{
    void eat();
}
public class ANNONYMOUS_INNER2 {
    public static void main(String args[]){
        Eatable e=new Eatable(){
            public void eat(){System.out.println("nice fruits");}
        };
        e.eat();
    }
}
/*
Internal working of given code
It performs two main tasks behind this code:

Eatable p=new Eatable(){
void eat(){System.out.println("nice fruits");}
};


A class is created but its name is decided by the compiler which implements the Eatable interface and provides the implementation of the eat() method.
An object of Anonymous class is created that is referred by p reference variable of Eatable type.
 */

/*
Internal class generated by the compiler
import java.io.PrintStream;
static class TestAnonymousInner1$1 implements Eatable
{
TestAnonymousInner1$1(){}
void eat(){System.out.println("nice fruits");}
}
 */