interface Showable{
    void show();
    interface Message{
        void msg();
    }}
    public class NESTED_INTERFACE1 implements Showable.Message {
    public void msg(){System.out.println("Hello nested interface");}

    public static void main(String args[]){
        Showable.Message message=new NESTED_INTERFACE1();//upcasting here
        message.msg();
    }
}
/*
Internal code generated by the java compiler for nested interface Message
The java compiler internally creates public and static interface as displayed below:.
public static interface Showable$Message
{
  public abstract void msg();
}

 */