//with instance method

public class STATIC_NESTED_CLASS {
    static int data=30;
    static class Inner{
        void msg(){System.out.println("data is "+data);}
    }
    public static void main(String args[]){
        STATIC_NESTED_CLASS.Inner obj=new STATIC_NESTED_CLASS.Inner();
        obj.msg();
    }
}
/*
Internal class generated by the compiler
import java.io.PrintStream;
static class TestOuter1$Inner
{
TestOuter1$Inner(){}
void msg(){
System.out.println((new StringBuilder()).append("data is ")
.append(TestOuter1.data).toString());
}
}
 */